spring:
  config:
    activate:
      on-profile: real
  profiles:
    group:
      real:
        - oauth
        - real-db

  session:
    store-type: jdbc
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect