spring:
  session:
    store-type: jdbc
    jdbc.initialize-schema: always
#      데이터베이스가 embeded 데이터베이스가 아니라면 자동생성되지 않으므로 위의 설정 추가

  profiles:
    include: oauth

  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:tcp://localhost/~/webservicedb;MODE=MYSQL
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
