spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
#        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
